### PR TITLE
fix: deref url and make combo of readme names

### LINKED ISSUE #434: `glow github.com/owner/repo` doesn't work with lowercase "readme.md" file
`glow https://github.com/danielwerg/r6api.js` returns `Error: can't find README in GitHub repository`

Looks like it is because glow looks strictly for `README` and `README.md` and nothing else.
https://github.com/charmbracelet/glow/blob/d9bf3b8ee89072cdec42af6d938a1bef0393c748/main.go#L31
Could it be solved by just adding `readme.md` to that ^ list?

### PR DESCRIPTION
**Pull request by jolheiser**
Resolves #434 

As well, fixes a subtle bug where the loop was using a pointer and the resulting URL was incorrect after a single iteration.

### CODE REVIEW

**Comment by danielwerg** [comment]
https://github.com/charmbracelet/glow/pull/436 I was late :D

**Comment by jolheiser** [comment]
> #436 I was late :D

Ah sorry! I saw this pop up and was curious, then got nerd-sniped. 😅

**Comment by danielwerg** [comment]
Also while we at it, it would probably be worth supporting `Readme`, `Readme.md`, `ReadMe` and `ReadMe.md`

**Comment by jolheiser** [comment]
> Also while we at it, it would probably be worth supporting `Readme`, `Readme.md`, `ReadMe` and `ReadMe.md`

Due to how this checks naively it might be more work than worth to make a matrix of all possibilities.  
Perhaps an improvement would be to use the API to do a more robust check.

**Comment by danielwerg** [comment]
https://docs.github.com/en/rest/repos/contents#get-a-repository-readme

**Comment by jolheiser** [comment]
> https://docs.github.com/en/rest/repos/contents#get-a-repository-readme

Looks fine to me, could probably even do it without importing the entire `go-github` lib. 
I'm afraid I won't be able to until later, so whether this PR is merged or gets superseded are both fine to me.

**Comment by danielwerg** [comment]
> Looks fine to me, could probably even do it without importing the entire `go-github` lib. I'm afraid I won't be able to until later, so whether this PR is merged or gets superseded are both fine to me.

https://github.com/charmbracelet/glow/pull/438

**Comment by caarlos0** [comment]
this should be fixed by #450

**Comment by caarlos0** [comment]
thanks for the pr, and sorry for the delay!

**Pull request closed without merging**
