### PR TITLE
Simplify contributor onloading with Gitpod

### PR DESCRIPTION
**Pull request by JesterOrNot**
## With Gitpod you will be able to:
* Run the project within the browser
* Contributors won't have to set-up the project at all
* Provides VSCode like editing in the browser

***Try it out***
https://gitpod.io/#github.com/JesterOrNot/glow

### CODE REVIEW

**Comment by muesli** [comment]
Thanks for your contribution @JesterOrNot! Technically your PR seems sound, however none of the glow developers have ever used gitpod and so we can't currently test it. 

As it's a pretty self-contained change, I'll keep the PR open for now.

**Comment by JesterOrNot** [comment]
image

**Comment by jessemillar** [comment]
The functionality of this PR might be partially duplicated by the new [GitHub Codespaces](https://github.com/features/codespaces/) feature.

**Comment by caarlos0** [comment]
This is not something we have in mind for the future of the project, therefore, I'm closing it. You can reply/reopen if you disagree :) 

Thanks!

**Pull request closed without merging**
