### PR TITLE
Added man page

### PR DESCRIPTION
**Pull request by ifrendas**
Adds a man page in glow.1

### CODE REVIEW

**Comment by muesli** [comment]
Thanks @ifrendas. Will pull this is shortly, but I'm also currently checking out a way to generate man pages from our code. We'll probably end up with a mix of your template and auto-generated text.

**Comment by bashbunni** [comment]
[This PR](https://github.com/cli/cli/pull/915) might be helpful for generating man pages auto-magically 🤔

**Comment by caarlos0** [comment]
refs #389

**Comment by caarlos0** [comment]
fixed on master

**Pull request closed without merging**
