### PR TITLE
docs: streamline install instructions

### PR DESCRIPTION
**Pull request by jonaustin**
Add a note to just use `go install` for installation.

Perhaps obvious, but I tend to simply use go as a package manager for golang projects.

Edit: Also, this is just super nice; been looking for a good terminal markdown viewer and this renders beautifully, thanks!

### CODE REVIEW

**Comment by jonaustin** [comment]
hmm...I'm fairly new to golang, and after poking at this a bit more; while go install makes installing packages easy; there's apparently no way to easily upgrade those packages after the install without using a 3rd party tool (e.g. https://github.com/TekWizely/bingo )

so I guess I'll close this to avoid confusion when folks want to upgrade after using `go install`.

**Comment by muesli** [comment]
Adding a `go install` command to the README isn't actually the worst idea. Probably below the `go build` instructions as it mostly targets other Go developers & users.

**Comment by jonaustin** [comment]
oh, yeah, I meant to re-open this after I realized that's just normal with Go; thanks, reopened :+1:

**Comment by jonaustin** [comment]
by the way -- all the charm stuff just looks fantastic, great example of why OSS is wonderful!

**Comment by jonaustin** [comment]
@bashbunni Sure thing! I should have a chance to refactor it this weekend.

**Comment by jonaustin** [comment]
@bashbunni Should be good now =)

**Review by bashbunni — APPROVED** [review]
Awesome, thanks so much!

**Pull request merged**
