### PR TITLE
Add support for GLOW_CONFIG_PATH environment variable

### LINKED ISSUE #292: Support GLOW_CONFIG environment variable as an alternative to setting --config flag
It will be helpful to have a GLOW_CONFIG environment variable to set the glow config file:

```bash
> GLOW_CONFIG=/path/to/glow.yml glow
```

### PR DESCRIPTION
**Pull request by vinicio**
Hi, everyone!

First of all, thanks for creating and maintaining this incredible tool!

I created this PR to add support for `GLOW_CONFIG` environment variable, like described in the issue linked here.

I had some doubts about updating the README.md file with extra config information, so feel free to give me your opinion.

Thank you!

Close #292

### CODE REVIEW

**Comment by meowgorithm** [comment]
Hi! Just a note that this PR should probably also cover the paths in the `glow config` command when the environment variable is set ([here](https://github.com/charmbracelet/glow/blob/8fc9a300a4494bd6f9dc0255f638c42163a168a4/config_cmd.go)).

Separately, I wonder if the variable should be named `GLOW_CONFIG_PATH`, just so that it's very clear that the variable is pointing to a file, rather than containing configuration itself.

**Comment by vinicio** [comment]
You are right, I forgot about the `config` command. I also isolated the variable name in a single const to make it easier to use.

**Comment by W1M0R** [comment]
Thanks @vinicio for your implementation!

**Comment by bashbunni** [comment]
@muesli if you can give me steps on what to test here I'm happy to help

**Pull request closed without merging**
